import type { Metadata } from 'next'
import { Nunito, Roboto_Condensed } from 'next/font/google'
import '../styles/globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import React from "react";

const primaryFont = Nunito({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-secondary',
})

const secondaryFont = Roboto_Condensed({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-secondary',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang='es'
			className={`${primaryFont.variable} ${secondaryFont.variable}`}
		>
			<body className={primaryFont.className}>
				<Navbar />
				<main className='container'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
